### ISSUE TITLE
ls client silently ignores errors

### ISSUE THREAD

**Issue by Thinkofname** [jonathandturner/rustls_vscode#7]
https://github.com/jonathandturner/rustls_vscode/blob/207168cec4a71b3d07b140004b3aca663e549741/ls_client/src/extension.ts#L14

Would be useful when testing the extension if it was logged to console or something otherwise getting the backtrace of a crash is hard.

**Comment by nrc** [comment]
With the linked commit, you can set DEV_MODE = true in the VS code extension and you'll get stderr output.

We also dump log info to a log file in your temp dir.
